---

- name: Install epel release on centos
  ansible.builtin.yum:
    name: Epel-release
  when: (ansible_facts['distribution'] == "CentOS")

- name: Install epel-release on amazonlinux
  ansible.builtin.command:
    cmd: amazon-linux-extras install epel -y
  when: (ansible_facts['distribution'] == "Amazon")

- name: Install system packages and utils on centos
  ansible.builtin.yum:
    name:
      [
        "which",
        "git",
        "telnet",
        "git-core",
        "wget",
        "python3-pip",
        "zip",
        "vim",
        "vim-common",
        "curl",
        "util-linux-user",
        # "ntp",
        "openssl",
        "rsyslog",
        "htop",
        # "perl-JSON-XS",
        "figlet",
      ]
    state: "{{ state }}"
    update_cache: true
  changed_when: false

- name: Install util-linux-use on centos
  ansible.builtin.yum:
    name: Yum-utils
    state: "{{ state }}"
    update_cache: true
  changed_when: false
  when: (ansible_facts['distribution'] == "CentOS")

- name: Install util-linux-user on amazon
  ansible.builtin.yum:
    name: Util-linux-user
    state: "{{ state }}"
    update_cache: true
  changed_when: false
  when: (ansible_facts['distribution'] == "Amazon")

- name: Install python packages
  ansible.builtin.yum:
    name:
      - awscli
      - iotop
    state: "{{ state }}"
  when: aws
